name: PR Test Report

on:
  workflow_run:
    workflows: ["Upload Test Results"]
    types:
      - completed

jobs:
  report:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          run-id: ${{ github.event.workflow_run.id }}

      - name: Report Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: test-results/results.xml
          reporter: java-junit  # Change to your actual format